apps/polls/urls.py
from django.urls import path, re_path
from . import views

app_name="polls"
urlpatterns = [
    re_path('^$', views.index, name="index"),
    re_path(r'^(?P<id>\d+)/', views.detail, name="detail"),
    re_path(r'^vote/', views.vote, name="vote"),



    ]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("apps.polls.urls", namespace="polls")),
]

apps/polls/models.py
from django.db import models


class District(models.Model):
    district_name = models.CharField(max_length=100)

    def __str__(self):
        return self.district_name


class Candidate(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    candidate_name = models.CharField(max_length=100)
    candidate_no = models.CharField(max_length=100)
    party = models.CharField(max_length=100)
    remarks = models.TextField()
    img_link = models.TextField()
    no_of_vote = models.IntegerField(default=0)


    def __str__(self):
        return self.candidate_name

class Voter(models.Model):
    candidate = models.ForeignKey(Candidate , on_delete=models.CASCADE)
    voter_name = models.CharField(max_length=100, blank=True)
    voter_text = models.TextField(blank=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.voter_name

apps/polls/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import District, Candidate

def index(request):
    district_list = District.objects.all()
    return render(request, "polls/index.html", locals())

def detail(request, id=None):
    district = District.objects.get(id=id)


    return render(request, "polls/detail.html", locals())

def vote(request):
    try:
        if request.POST:

            candidate = Candidate.objects.get(id=request.POST['candidate_id'])
            candidate.no_of_vote += 1
            candidate.save()
    except:
        candidate = None
    return render(request, "polls/vote.html", locals())

apps/polls/templates/polls/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>{% block title %}My Posts{% endblock title %}</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<style>{% block style%}{% endblock style %}</style>
</head>
<body>
{% include "polls/includes/_navbar.html" %}
{% include "polls/includes/messages_display.html" %}


<div class="container">
    {% block content %}



    {% endblock content %}
  </div>


  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

apps/polls/templates/polls/detail.html
{% extends "polls/base.html" %}

<style>
{% block style %}
  img{
    object-fit:cover;
  }
{% endblock style %}
</style>

{% block content %}
<form method="POST" action="{% url "polls:vote" %}">{% csrf_token %}
{% for candidate in district.candidate_set.all %}
<a href="{% url "polls:index" %}"><img src="{{candidate.img_link}}" alt="image" width="200" height="180"></a><br>
{{candidate.candidate_no}}
{{candidate.candidate_name}}<br>
現有票數 {{candidate.no_of_vote}}<br>
投票 <input type="radio" name="candidate_id" value="{{candidate.id}}">
<br><br>
<input type="submit" value="submit"><br><br>
<hr>
{% endfor %}

</form>
{% endblock content %}

apps/polls/templates/polls/includes/_navbar.html
<nav class="navbar navbar-default">
{% load static %}
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/admin/">Login</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url "polls:index" %}">Home</a></li>
            <li><a href="/polls/1/">香港島</a></li>
            <li><a href="/polls/2/">九龍西</a></li>
            <li><a href="/polls/3/">新界東</a></li>
            <li><a href="/polls/4/">建築、測量、都市規劃及園境界</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

apps/polls/templates/polls/includes/messages_display.html
{% if messages %}
  <div class="messages">
    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message | safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>
  </div>
{% endif %}

apps/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block content %}
<ul>
{% for district in district_list %}
<li><a href="{% url "polls:detail" id=district.id %}">{{district.district_name}}</a></li><br>
{% endfor %}
</ul>
<br><br>

{% endblock content %}

apps/polls/templates/polls/vote.html
{% extends "polls/base.html" %}

{% block content %}
{% if candidate %}
<img src="{{candidate.img_link}}" alt="image">
{{candidate.candidate_name}}<br><br>
現有票數 {{candidate.no_of_vote}}<br><br>
<a href="{% url "polls:index" %}"><button>Back</button></a>
{% else %}
<h1>You must choose a candidate.</h1><br><br>
<a href="{% url "polls:index" %}"><button>Back</button></a>
{% endif %}

{% endblock content %}